Second version of marionnet with a support for X11-forwarding not based on the ghost interface eth42. This version works well but is not completely finished on the marionnet's code side (however, what is missing are details). On the other hand, it lacks to build new virtual machines exploiting this new X11-forwarding system based on pseudo-terminal. The little script "uml/guest/make-tarball-for-guest-system.sh" builds easily a tarball, with all the stuff (/etc/init.d/marionnet-{relay,dummy-xserver}, /usr/bin/marionnet-dummy-xservice), ready to be extracted in the root directory of the guest filesystem. Here a short summary of the mechanism:
                   HOST SIDE                 |          GUEST SIDE
                                             |
[] <======-marionnet-fork-or-thread-======>[]|[]<=========-socat-=========>[]
unix/inet                     pseudo-terminal|serial port    /tmp/.X11-uix/X0
X11 server socket            Ex:"/dev/pts/29"|Ex:"/dev/ttyS4"     unix socket
Ex:(inet 127.0.0.1:6010)                     |

The "socat" service is launched by marionnet-dummy-xservice, once the connexion established by marionnet-dummy-xserver (itself based on socat). 
To tell the story in more details, marionnet-dummy-xserver accepts connections from the Unix socket "/tmp/.X11-unix/Xd" (corresponding to DISPLAY=:d.0) and, for an accepted connexion, starts the script marionnet-dummy-xservice that do the job. Basically, this job is nothing more than a "socat" service (/usr/bin/socat, see "man socat") connecting this socket to an available (simulated) serial port in the range /dev/ttySx. The UML kernel will be kind enough to provide an associated pseudo-terminal (/dev/pts/x) on host side, and marionnet.native, running on host side, will provide the rest of connection from the good pseudo-terminal to the real X11 server. The marionnet-dummy-xserver is itself implemented with /usr/bin/socat (instead of another "native-program" of this repository) in order to facilitate the installation of all the necessary stuff in the guest GNU/Linux systems.

diff --git a/uml/guest/marionnet-relay b/uml/guest/marionnet-relay
--- a/uml/guest/marionnet-relay
+++ b/uml/guest/marionnet-relay
@@ -19,7 +19,7 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 ### BEGIN INIT INFO
-# Provides:          marionnet-startup
+# Provides:          marionnet-relay
 # Required-Start:    $local_fs $network $syslog
 # Required-Stop:
 # Should-Start:
@@ -50,6 +50,10 @@ fi
 # Fix the PATH:
 export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 
+function not_found_error_notification {
+  echo "ERROR: command not found:  $1  (but we keep going)" 1>&2
+}
+
 # ======================================================== #
 #                        START ()                          #
 # ======================================================== #
@@ -57,6 +61,12 @@ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 function start {
 
  echo -n "Marionnet startup configuration... "
+
+ # ---
+ # Dependencies' errors:
+ for i in ifconfig ping ping6 hostname mount ip route xauth sed grep chmod chown socat; do
+   type -p $i &>/dev/null || not_found_error_notification $i;
+ done
 
  function append_line_if_needed {
   local LINE="$1"
@@ -279,6 +289,25 @@ fi
    ip addr del $ip42/16 dev eth42
  else
    DISPLAY_VALUE=172.23.0.254:${x11_display_number:-0}
+ fi
+
+ # ---------------------------
+ # Marionnet X11 dummy server?
+ # ---------------------------
+ XSERVER="/etc/init.d/marionnet-dummy-xserver"
+ XSERVICE="marionnet-dummy-xservice"
+ # ---
+ # Change the DISPLAY if eth42 is not running (disabled with Marionnet), or
+ # if the machine includes all the stuff to bypass eth42 and the marionnet-daemon:
+ # ---
+ if ! ifconfig eth42 up &>/dev/null || \
+  { test -x "$XSERVER" && type &>/dev/null -p "$XSERVICE"; }
+ then
+   # Clean directory .X11-unix
+   DISPLAY_VALUE=:${x11_display_number:-":0.0"}
+   mkdir -p /mnt/hostfs/.X11-unix
+   rm -f /mnt/hostfs/.X11-unix/*
+   chmod a+rwx /mnt/hostfs/.X11-unix
  fi
 
  # Support for `ssh' tunnelling:
