marionnet_from_scratch specialized for debian or derived distributions.

diff --git a/useful-scripts/marionnet_from_scratch b/useful-scripts/marionnet_from_scratch
--- a/useful-scripts/marionnet_from_scratch
+++ b/useful-scripts/marionnet_from_scratch
@@ -16,14 +16,18 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# Script version: 0.92
+# Script version: 0.93
 
 set -e
 shopt -s nullglob
 shopt -s expand_aliases
 
-# By default SUDO is sudo:
-export SUDO=sudo
+# By default SUDO is 'sudo' for the normal user:
+if [[ $USER = root ]]; then
+  export SUDO=eval
+else
+  export SUDO=sudo
+fi
 
 # =============================================================
 #                     SELF DEPENDENCIES
@@ -384,6 +388,48 @@ function tmpfile {
 #                           TOOLS
 # =============================================================
 
+function exit_and_continue_as_root {
+# global TWDIR COMMAND_LINE
+echo
+if [[ -n "$1" ]]; then
+  echo "Error using the program '$1' to become the super user."
+else
+  echo "No manner to become the super user."
+fi
+echo -e "In order to install marionnet, become super user and continue launching
+the following command:
+---
+$COMMAND_LINE -c $TWDIR
+---
+Exiting."
+exit 1
+}
+
+function ensure_sudo {
+# global USER TWDIR COMMAND_LINE
+[[ $USER = root ]] && return 0
+sudo -v "$@" || exit_and_continue_as_root "sudo"
+}
+
+function ensure_sudo_or_continue_as_root {
+# global USER TWDIR COMMAND_LINE
+local MESSAGE_ABOUT_ACTION="$1"
+if [[ $USER = root ]]; then
+  echo "Fine, I'm root." 1>&2
+elif type -t sudo 1>&2; then
+  ensure_sudo -p "* Required the [sudo] password for %u:"
+elif type -t su 1>&2; then
+  echo "* $MESSAGE_ABOUT_ACTION"
+  echo "  The script will be continued as root."
+  echo -n "  Please provide root's password: "
+  su -c "echo; $COMMAND_LINE -c $TWDIR" || exit_and_continue_as_root "su"
+  exit 0
+else
+  exit_and_continue_as_root
+fi
+}
+
+
 function append_line_if_needed {
 # global SUDO
 local LINE="$1"
@@ -442,11 +488,17 @@ function wait_printing_percent_progress {
 
 function launch_and_log {
  # global COMMAND_RESULT ALREADY_DONE SUDO
- # The option --script implies that the command will be launched
- # with $SUDO; otherwise the command is executed with eval
+ # The option --as-root implies --as-script if the user in not root (in order to
+ # prevent sudo to re-ask the password)
+ # The option --as-script implies that the command will be launched
+ # as a standalone script
+ local EVAL_OR_SUDO
  local AS_SCRIPT
- if [[ $1 = --script || $1 = --as-script ]]; then
-   shift
+ # By default EVAL_OR_SUDO is equal to eval
+ EVAL_OR_SUDO=eval
+ if [[ $1 = --as-root   || $1 = --sudo   ]]; then shift; EVAL_OR_SUDO=$SUDO; fi
+ if [[ $1 = --as-script || $1 = --script ]]; then shift; AS_SCRIPT=yes; fi
+ if [[ $EVAL_OR_SUDO = sudo ]]; then
    AS_SCRIPT=yes
  fi
  local MSG="$1"
@@ -467,10 +519,10 @@ function launch_and_log {
      echo "export PATH=$PATH" >> $TMPSCRIPT
      echo $CMD >> $TMPSCRIPT
      chmod +x $TMPSCRIPT
-     $SUDO $TMPSCRIPT &
+     $EVAL_OR_SUDO $TMPSCRIPT &
      ;;
      *)
-     eval $CMD &
+     $EVAL_OR_SUDO $CMD &
      ;;
  esac
  wait_printing_percent_progress $SECTION_SIZE
@@ -606,6 +658,70 @@ function download_latest_graphviz {
 }
 
 # =============================================================
+#                     DEBIAN or derived
+# =============================================================
+
+function are_we_in_debian_or_derived {
+  $(which dpkg) -L bash 2>/dev/null | grep -q $(which bash) &&
+  $(which dpkg) -L apt  2>/dev/null | grep -q $(which apt-get)
+}
+
+function echo_debian_package_for_binary_if_really_needed {
+ local BINARY=$1
+ local PACKAGE=$2
+ if type -t $BINARY 1>&2; then
+   return 0 # not needed
+ else
+   echo "$PACKAGE " # note the trailing blank
+ fi
+}
+
+function is_aptitude_installed  {
+ type 1>&2 aptitude
+}
+
+function echo_required_debian_packages {
+ local LIST i VDE2_VERSION
+
+ # Then continue with aptitude
+ for i in gcc make flex libtool bison grep tar xterm wget diff mktemp realpath sed gawk; do
+   LIST+=$(echo_debian_package_for_binary_if_really_needed $i $i)
+ done
+
+ LIST+=$(echo_debian_package_for_binary_if_really_needed dot graphviz)
+ LIST+=$(echo_debian_package_for_binary_if_really_needed uml_switch uml-utilities)
+
+ for i in \
+   libgtk2.0-dev libglade2-dev \
+   bridge-utils coreutils debianutils \
+   net-tools uml-utilities util-linux x11-xserver-utils \
+   coreutils findutils login procps \
+   rlfe; # alternatives are rlwrap and ledit
+   do
+   if ! dpkg -p $i 1>&2; then
+     LIST+="$i "
+   fi
+ done
+
+ # vde2 only if is not already installed and the available version is >= 2.2.1
+ type 1>&2 vde_switch || {
+   VDE2_VERSION=$(aptitude show vde2 | awk '/^Version.*2[.]2[.][0-9].*/ {print $2}' | awk -F '-' '{print $1}')
+   VDE2_VERSION=$(echo $VDE2_VERSION | awk -F '.' '(($2 * 100 + $3 * 10 + $4) >= 221) {print}')
+   if [[ -n "$VDE2_VERSION" ]]; then
+     LIST+="vde2 "
+   fi
+ }
+
+ # x86_64 => libc6-i386
+ if type uname && [[ $(uname -m) = "x86_64" ]] && ! dpkg -p libc6-i386; then
+   LIST+="libc6-i386 "
+ fi 1>&2
+
+ # Return the list:
+ echo "$LIST"
+}
+
+# =============================================================
 #                            MAIN
 # =============================================================
 
@@ -636,6 +752,27 @@ touch $COMMAND_RESULT
 
 OUR_BASE_URL="http://www.marionnet.org/download/marionnet_from_scratch"
 OUR_MIRROR="$OUR_BASE_URL/mirror/"
+
+if are_we_in_debian_or_derived; then
+  echo "* This looks like a Debian or derived distribution. Oh, joy!"
+  DEBIAN_PACKAGE_LIST=$(echo_required_debian_packages)
+  echo "DEBIAN_PACKAGE_LIST=$DEBIAN_PACKAGE_LIST" 1>&2 # debugging
+  if [[ -n ${DEBIAN_PACKAGE_LIST%% } ]]; then
+    echo "  Required packages: $DEBIAN_PACKAGE_LIST"
+    echo -n "  Do I install required package(s) with aptitude ([y]/n)? "
+    read z
+    if [[ $z != n && $z != N ]]; then
+      MSG="Installing required packages with aptitude"
+      ensure_sudo_or_continue_as_root "* $MSG"
+      # First install aptitude if needed:
+      if ! type 1>&2 aptitude; then
+        launch_and_log --sudo "Installing aptitude" "apt-get -y install aptitude"
+      fi
+      launch_and_log --sudo "$MSG" "aptitude -q -y install $DEBIAN_PACKAGE_LIST"
+      DISABLE_libc6_i386_WARNING=yes
+    fi # answered yes
+  fi # package list not empty 
+fi # are_we_in_debian_or_derived
 
 launch_and_log "Downloading marionnet" download_latest_marionnet 22400
 launch_and_log "Downloading ocamlbricks" download_latest_ocamlbricks 7500
@@ -715,12 +852,12 @@ cat >CONFIGME <<EOF
 libraryprefix=$LIB_OCAML
 prefix=$PREFIX
 configurationprefix=\$prefix/etc
-documentationprefix=\$prefix/doc
-localeprefix=\$prefix/locale
+documentationprefix=\$prefix/share/doc
+localeprefix=\$prefix/share/locale
 ocaml_sources=$LIB_OCAML/caml
 EOF
 
-launch_and_log "Compiling ocamlbricks" 'make && make install' 4002673
+launch_and_log "Compiling ocamlbricks" 'make clean && make && make install' 4002673
 cd ..
 
 # =============================================================
@@ -730,13 +867,15 @@ cd ..
 cd marionnet
 cp ../ocamlbricks/CONFIGME .
 
+# make
+
 case $GENERATE_BYTECODE in
  yes)
-  MARIONNET_MAKE_COMMAND='make byte'
+  MARIONNET_MAKE_COMMAND='make clean byte'
   WEIGHT=2460914 
   ;;
  no) 
-  MARIONNET_MAKE_COMMAND='make native'
+  MARIONNET_MAKE_COMMAND='make clean native'
   WEIGHT=2780316
   ;;
 esac
@@ -746,43 +885,20 @@ launch_and_log \
   "$MARIONNET_MAKE_COMMAND" \
   $WEIGHT
 
-function exit_and_continue_as_root {
-# global TWDIR COMMAND_LINE
-echo
-if [[ -n "$1" ]]; then
-  echo "Error using the program '$1' to become the super user."
-else
-  echo "No manner to become the super user."
-fi
-echo -e "In order to install marionnet, become super user and continue launching
-the following command:
----
-$COMMAND_LINE -c $TWDIR
----
-Exiting."
-exit 1
-}
-
-function ensure_sudo {
-[[ $USER = root ]] && return 0
-sudo -v "$@" || exit_and_continue_as_root "sudo"
-# The following is really needed, otherwise sudo reask the password
-# executing a new sudo in a foreground job:
-sudo -v; sync; sleep 1
-}
+# make install
 
 if [[ $USER = root ]]; then
   MAKE_INSTALL='make install'
   # Redefine SUDO:
   SUDO=eval
-  unset AS_SCRIPT
+  unset AS_ROOT
 elif [[ -w "$PREFIX" ]]; then
   MAKE_INSTALL='make install'
-  unset AS_SCRIPT
+  unset AS_ROOT
 elif type -t sudo 1>&2; then
   ensure_sudo -p "* Required the [sudo] password for %u:"
   MAKE_INSTALL="PATH=$PATH make install"
-  AS_SCRIPT=--script
+  AS_ROOT=--as-root
 elif type -t su 1>&2; then
   echo "* Preparing to install in $PREFIX"
   echo "  The script will be continued as root."
@@ -793,7 +909,7 @@ else
   exit_and_continue_as_root
 fi
 
-launch_and_log ${AS_SCRIPT} \
+launch_and_log ${AS_ROOT} \
   "Installing marionnet" \
   "$MAKE_INSTALL" \
   3918924 # weight
@@ -883,7 +999,7 @@ function download_our_kernels {
       "kernels_linux-2.6.18-ghost.tar.gz") WEIGHT=6032 ;;
       *) unset WEIGHT ;;
     esac
-    launch_and_log --script "Installing $i" "{ wget -O - '$OUR_BASE_URL/$i' | tar 1>&2 xvzf -; }" $WEIGHT
+    launch_and_log --sudo --script "Installing $i" "{ wget -O - '$OUR_BASE_URL/$i' | tar 1>&2 xvzf -; }" $WEIGHT
   done
 }
 
@@ -902,7 +1018,7 @@ function download_our_big_filesystems {
       "filesystems_machine-mandriva20100215.tar.gz") WEIGHT=540521 ;;
       *) unset WEIGHT ;;
     esac
-    launch_and_log --script "Installing $i" "{ wget -O - '$OUR_BASE_URL/$i' | tar 1>&2 xvzf -; }" $WEIGHT
+    launch_and_log --sudo --script "Installing $i" "{ wget -O - '$OUR_BASE_URL/$i' | tar 1>&2 xvzf -; }" $WEIGHT
   done
 }
 
@@ -919,7 +1035,7 @@ function download_our_pinocchio_filesystems {
       "filesystems_pinocchio.tar.gz") WEIGHT=77543 ;;
       *) unset WEIGHT ;;
     esac
-    launch_and_log --script "Installing $i" "{ wget -O - '$OUR_BASE_URL/$i' | tar 1>&2 xvzf -; }"  $WEIGHT
+    launch_and_log --sudo --script "Installing $i" "{ wget -O - '$OUR_BASE_URL/$i' | tar 1>&2 xvzf -; }"  $WEIGHT
   done
 }
 
@@ -943,6 +1059,45 @@ if [[ $IGNORE_BIG_FILESYSTEMS = yes ]]; then
 else download_our_big_filesystems; fi
 
 popd 1>&2
+
+
+# =============================================================
+#                     marionnet.conf
+# =============================================================
+
+MARIONNET_DOT_CONF=$PREFIX/share/marionnet/marionnet.conf
+
+function first_installed_binary_of_list {
+ local i
+ for i in "$@"; do
+   if type -t $i &>/dev/null; then
+     echo $i
+     return 0
+   fi
+ done
+ # otherwise return the first:
+ echo $1
+}
+
+MARIONNET_KEYBOARD_LAYOUT=$(echo $LANG | grep -o '^[a-z]*')
+MARIONNET_KEYBOARD_LAYOUT=${MARIONNET_KEYBOARD_LAYOUT=:-us}
+MARIONNET_PDF_READER=$(first_installed_binary_of_list evince okular kpdf xpdf gv)
+MARIONNET_POSTSCRIPT_READER=$MARIONNET_PDF_READER
+MARIONNET_DVI_READER=$MARIONNET_PDF_READER
+MARIONNET_HTML_READER=$(first_installed_binary_of_list firefox epiphany galeon konqueror rekonq chromium opera)
+MARIONNET_TEXT_EDITOR=$(first_installed_binary_of_list emacs gedit kate kwrite xemacs)
+
+for i in MARIONNET_{PDF,POSTSCRIPT,DVI,HTML}_READER MARIONNET_TEXT_EDITOR MARIONNET_KEYBOARD_LAYOUT; do
+ v=$(eval echo \$$i);
+ $SUDO sed -i -e "s/$i=\(.*\)/$i=$v/" $MARIONNET_DOT_CONF
+done
+
+if [[ ! -f /etc/marionnet/marionnet.conf ]]; then
+  echo -n "* Installing /etc/marionnet/marionnet.conf ..."
+  $SUDO mkdir -p /etc/marionnet/
+  $SUDO cp $MARIONNET_DOT_CONF /etc/marionnet/
+  echo_at_right_side --newline "ok"
+fi
 
 # =============================================================
 #                     SysV-style INIT
@@ -1134,6 +1289,50 @@ local i=$1
 $SUDO sed -i -e 's/\(^DisallowTCP=true.*\)$/#\1\nDisallowTCP=false/g' $i
 }
 
+# Sections in file have the form "[security]"
+function ensure_section_and_binding {
+[[ $# -ge 3 ]] || return 1
+local SECTION=$1   # ex: security
+local VARIABLE=$2  # ex: Enable
+local VALUE=$3     # ex: true
+local AWK_PROGRAM
+shift 3
+AWK_PROGRAM="
+   BEGIN {x=0}
+   /\[$SECTION\]/ {x=1;print;next}
+   (x==1) && /$VARIABLE=.*/ {print \"$VARIABLE=$VALUE\"; x=2; next}
+   (x==1) && /\[.*\]/       {print \"$VARIABLE=$VALUE\n\"; print; x=2; next}
+   /\[.*\]/ {print;next}
+   {print}
+   END {if (x==0) print \"[$SECTION]\"; if (x==0 || x==1) print \"$VARIABLE=$VALUE\n\";}"
+case $# in
+ 0) awk "$AWK_PROGRAM" ;;
+ *) 
+  local i
+  local TMPFILE=$(tmpfile)
+  for i in "$@"; do
+    awk 0<"$i" 1>$TMPFILE "$AWK_PROGRAM" 
+    cat $TMPFILE 1>"$i"   
+  done
+  rm $TMPFILE
+  ;;
+esac
+}
+
+# This is needed, for instance, for ubuntu 10.10
+function ensure_DisallowTCP_false_to_gdm_custom_dot_conf {
+# global SUDO CHANGED_FILES
+local custom=/etc/gdm/custom.conf
+local TMPFILE=$(tmpfile)
+cp $i $TMPFILE
+ensure_section_and_binding "security" "DisallowTCP" "false" $TMPFILE 
+ensure_section_and_binding "xdmcp" "Enable" "true" $TMPFILE
+if ! diff -q $custom $TMPFILE >/dev/null; then 
+  CHANGED_FILES+="$i "
+  $SUDO bash -c "cat $TMPFILE >$custom"
+fi
+}
+
 function apply_all_filters {
 # global CHANGED_FILES
 local i=$1
@@ -1151,10 +1350,15 @@ function adjust_X_display_manager {
 # global CHANGED_FILES
 local BACKUP=$(tmpfile)
 DIRS=$($SUDO find /etc/ -type d -name "?dm")
+if [[ -d /etc/X11/xinit ]]; then DIRS+=" /etc/X11/xinit/"; fi
 FILES=$($SUDO find $DIRS -name "*rc" -o -name "*.conf")
 FILES=$(for i in $FILES; do grep -l "^[a-ZA-Z0-9]*[=].*[-]nolisten tcp" $i; done)
 for i in $FILES; do apply_all_filters $i; done
 rm -f $BACKUP
+# A special case:
+if [[ -f /etc/gdm/custom.conf ]]; then
+  ensure_DisallowTCP_false_to_gdm_custom_dot_conf
+fi
 [[ -n $CHANGED_FILES ]]
 }
 
@@ -1207,12 +1411,13 @@ fi
 # =============================================================
 
 # 64-bit architecture warning:
-if type uname 1>&2 && [[ $(uname -m) = "x86_64" ]]; then
- echo '---'
- echo "* Warning: this is 64-bit architecture."
- echo "  => Make sure that the package libc6-i386 is installed."
+if [[ -z $DISABLE_libc6_i386_WARNING ]]; then
+ if type uname 1>&2 && [[ $(uname -m) = "x86_64" ]]; then
+  echo '---'
+  echo "* Warning: this is 64-bit architecture."
+  echo "  => Make sure that the package libc6-i386 is installed."
+ fi
 fi
-
 # =============================================================
 #                          Notes
 # =============================================================
@@ -1222,6 +1427,7 @@ echo '---'
 echo "* Notes:"
 echo "  - Install additional filesystem in" $PREFIX/share/marionnet/filesystems/
 echo "  - Install additional kernels in" $PREFIX/share/marionnet/kernels/
+echo "  - Customize your installation by editing /etc/marionnet/marionnet.conf"
 
 echo '---'
 echo "Success."
